import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import * as Tooltip from "@radix-ui/react-tooltip";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Tooltip.Provider>
          {/* 
            Esta div garante:
              - Centralização vertical e horizontal
              - Altura mínima igual a tela toda
              - Um fundo sutil 
          */}
          <div className="min-h-screen w-full flex items-center justify-center bg-gradient-to-br from-gray-50 via-white to-sky-50 ">
            {children}
          </div>
        </Tooltip.Provider>
      </body>
    </html>
  );
}
